### ISSUE TITLE
getting this error @ vue resource

### ISSUE THREAD

**Issue by danielschmitz** [danielschmitz/awesome-vue-typescript#1]
![image](https://cloud.githubusercontent.com/assets/1509692/16936195/3d59643a-4d3b-11e6-899e-e811b36296b7.png)

**Comment by itsFrank** [comment]
From the project, i don't see the vue-resource typings installed, try `typings install --save --global dt~vue-resource`

**Comment by itsFrank** [comment]
It should add $http to the Vue type definition and declate the 'vue-resource' module as well

**Comment by danielschmitz** [comment]
typings install --save --global dt~vue-resource works!!!

Tks

final result

![image](https://cloud.githubusercontent.com/assets/1509692/16948182/978770ac-4d89-11e6-8d96-b46be694f47b.png)

![image](https://cloud.githubusercontent.com/assets/1509692/16948198/b597c222-4d89-11e6-9b4a-a5598c2c630e.png)

![image](https://cloud.githubusercontent.com/assets/1509692/16948207/c57238c6-4d89-11e6-8e31-e40649cdf845.png)
